version: "3.8"
services:
  app:
    image: ghcr.io/christoffernorgaard/spiritapi:main
    volumes:
      - type: bind
        source: ./test.csv #location of mounted data
        target: /files/data.csv
    environment:
      - USERNAME=changeme #password of the spirit user
      - PASSWORD=changeme #user
    ports:
      - "3030:80" #port on which it servers
