version: "3.8"
services:
  app:
    image: 979b437610c1
    volumes:
      - type: bind
        source: ./test.csv
        target: /files/data.csv
    environment:
      - USERNAME=tester
      - PASSWORD=testing
    ports:
      - "3030:80"
